### PR TITLE
Logos update

### PR DESCRIPTION
**Pull request by ize-302**

### CODE REVIEW

**Comment by ichtrojan** [comment]
Hi @ozorku, thanks a lot for submitting this PR, can you compress these logos with [TinyPNG](https://tinypng.com) and update the PR?

**Comment by ichtrojan** [comment]
Also, can you edit/find a squared version of these logos to fit with the others

**Comment by ize-302** [comment]
> Hi @ozorku, thanks a lot for submitting this PR, can you compress these logos with [TinyPNG](https://tinypng.com) and update the PR?



> Also, can you edit/find a squared version of these logos to fit with the others

Sure thing

**Comment by ize-302** [comment]
I've also updated some previous logos to be squared e.g Kuda Bank, UBA, Asosavings

**Review by S-code652 — APPROVED** [review]

**Pull request merged**
