### PR TITLE
Added ussd codes to banks.json file

### PR DESCRIPTION
**Pull request by AbdQaadir**
I was able to include the ussd codes of 29 banks out of the 38 banks listed. Those without ussd are mostly microfinance banks.

### CODE REVIEW

**Comment by ichtrojan** [comment]
You failed to account for this change in `server.go`

**Comment by AbdQaadir** [comment]
I don't write Go, but I will try and read through the server.go and find way to account for the change

**Comment by AbdQaadir** [comment]
I have made changes to the server.go file, kindly check.

**Comment by ichtrojan** [comment]
#2 completed the feature, thanks -- could not find the changes requested in #1

**Pull request closed without merging**
