### PR TITLE
Add 2 endpoints

### PR DESCRIPTION
**Pull request by zikyfranky**
`/slug/{slug}` -> Gets the first exact match for slug 
`/code/{code}` -> Gets the first exact match for code

This addresses the #6 issue, this gets only the first match, can be easily modified to get an array instead AND/OR a partial match.

### CODE REVIEW

**Comment by ichtrojan** [comment]
Hey @zikyfranky,

Thanks for the PR -- I think we should have this in the main endpoint (`/`) but as query params with no support for partial match.

We can then have a search endpoint for partial match

**Comment by zikyfranky** [comment]
Great, I could refactor to work with that
I didn't go that route cause I didn't know what param to prioritize.

For example, someone sends a request like so `/?code=787&slug=random-bank`, which should take priority over the other.

**Comment by ichtrojan** [comment]
No one needs to take priority, treat it as SQL "and" query

**Comment by zikyfranky** [comment]
Hey @ichtrojan, I've been busy with stuff, just had the time to push the changes required and as stated.

Let me know if that works with what we intend to achieve.

**Pull request merged**
